### ISSUE TITLE
Self check process stuck

### ISSUE THREAD

**Issue by monouno** [DMOJ/judge-docker-medium#1]
Hi,
I tried to build a judge server with docker, but it stuck in the shelf-check process, and I had to abort the container, then I tried to debug with pdb, which seemed to be stuck in this:
```
> /judge/dmoj/cptbox/sandbox.py(409)_communicate()
-> if input_offset >= len(input):
(Pdb) n
> /judge/dmoj/cptbox/sandbox.py(410)_communicate()
-> close_unregister_and_remove(fd)
(Pdb) n
> /judge/dmoj/cptbox/sandbox.py(398)_communicate()
-> for fd, mode in ready:
(Pdb) n
> /judge/dmoj/cptbox/sandbox.py(390)_communicate()
-> while fd2file:
(Pdb) n
> /judge/dmoj/cptbox/sandbox.py(391)_communicate()
-> try:
(Pdb) n
> /judge/dmoj/cptbox/sandbox.py(392)_communicate()
-> ready = poller.poll()
(Pdb) n
```

```
~$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

Ubuntu Server 16.04 STL amd64

**Comment by Xyene** [comment]
This looks like https://github.com/DMOJ/judge/issues/213

Basically, `PTRACE_TRACEME` was hardened on Ubuntu recently (https://wiki.ubuntu.com/SecurityTeam/Roadmap/KernelHardening#ptrace_Protection) so now the judge requires root to run. Since this is suboptimal for online judges, it can be disabled with

```
$ echo 0 > /proc/sys/kernel/yama/ptrace_scope
```

The judge should be printing a better error message than hanging entirely, but that's more the scope of https://github.com/DMOJ/judge/issues/213

**Comment by quantum5** [comment]
I don't think it was the 7 year old change in Ubuntu that's causing the problem.

That particular kernel setting is to blame though: [see the kernel documentation](https://www.kernel.org/doc/Documentation/security/Yama.txt).

Its value has to be either 0 or 1 for DMOJ to work. Any value greater will prevent the use of DMOJ.

**Comment by Xyene** [comment]
Looks like there's a bit more involved: https://bitworks.software/blog/en/2017-07-24-docker-ptrace-attach.html

> We tried to put “0” value into `/proc/sys/kernel/yama/ptrace_scope` but failed because we got “`/proc` is read only” message.
> 
> We overcame that “read-only procfs” limitation by running our container in “privileged” execution mode setting “–privileged” docker run flag.

**Comment by monouno** [comment]
It work after the addition of  ‘--privileged=true‘.
But is this configuration safe?

**Comment by Xyene** [comment]
I think it'd end up no more or less safe than running the judge outside of Docker.

The DMOJ judge contains a good sandbox implementation that can run with minimal privileges outside of Docker (i.e. a non-root account); if anything, Docker would only be useful for simplified deployment as opposed to extra security (though the judge requires two lines to install anyway, which is why we haven't been maintaining these packages).

If you particularly want to grant only what is necessary to Docker, you could grant specific capabilities (https://linux.die.net/man/7/capabilities) with Docker's `--cap-add` flag until you find the right combination that allows `ptrace(2)` to work.

**Comment by monouno** [comment]
I get it.
